name: CICD

on:
  push:
    tags:
      - v* 
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: '16'
    - uses: actions/cache@v3
      with:
        path: |
            **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-${{ steps.node.outputs.version }}
    - name: run ls
      run: ls
    - name: install package
      run: npm install
    - name: build
      run: npm run build
    - name: run echo context temp test
      env: 
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo ${{ runner.os }}-node_modules-${{ steps.commit.outputs.short }}
    - name: run echo2 context temp test
      env: 
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo ${{ runner.os }}-node_modules-${{github.sha}}
  
  retrieve-cache:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
            **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-${{ steps.node.outputs.version }}
    - name: run ls
      run: ls
  
  push-sssm-app-server-image:
    if: github.ref_type == 'tag' && contains(github.ref_name, 'v')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: run ls
      run: ls