name: CICD

on:
  create:
    tags:
      - v* 

jobs:
  push-sssm-app-server-image:
      runs-on: ubuntu-latest
      steps:
      - name: run ls
        run: ls
      - name: run echo context
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"