name: CICD

on:
  push:
    tags:
      - v* 
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: run ls
      run: ls
    - name: run echo context temp test
      env: 
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
  
  push-sssm-app-server-image:
    if: github.ref_type == 'tag' && contains(github.ref_name, 'v')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: run ls
      run: ls